// Manifesto de filtragem - ENEM 2023, 1º dia, Caderno 1 Azul, aplicação regular
// Não contém os enunciados completos; serve para controlar ingestão, gabarito e mídias.
// Segurança: todos os registros permanecem verified=false até a validação integral do conteúdo.

export const enem2023D1Caderno1FilterManifest = {
  "exam": {
    "name": "ENEM",
    "year": 2023,
    "applicationType": "regular",
    "day": 1,
    "bookletNumber": 1,
    "bookletColor": "blue",
    "objectiveItemCount": 95,
    "readyTextCount": 84,
    "imageRequiredCount": 11,
    "hasEssayPrompt": true,
    "essayPromptExternalId": "ENEM-2023-D1-C1-REDACAO",
    "essayPromptSourcePage": 19,
    "notes": "95 itens objetivos armazenáveis: 5 inglês + 5 espanhol + questões comuns 6-90. O candidato responde apenas um dos dois blocos de língua estrangeira.",
    "verificationPolicy": "Não inserir no officialQuestionBank enquanto verified=false. Alterar para true apenas após validar enunciado, alternativas, gabarito, metadados e mídia, quando houver."
  },
  "items": [
    {
      "externalId": "ENEM-2023-D1-C1-ING-01",
      "questionNumber": 1,
      "languageTrack": "english",
      "area": "languages",
      "answerKey": "B",
      "sourcePage": 2,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-ING-02",
      "questionNumber": 2,
      "languageTrack": "english",
      "area": "languages",
      "answerKey": "B",
      "sourcePage": 2,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-ING-03",
      "questionNumber": 3,
      "languageTrack": "english",
      "area": "languages",
      "answerKey": "D",
      "sourcePage": 2,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-ING-04",
      "questionNumber": 4,
      "languageTrack": "english",
      "area": "languages",
      "answerKey": "A",
      "sourcePage": 3,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-ING-05",
      "questionNumber": 5,
      "languageTrack": "english",
      "area": "languages",
      "answerKey": "B",
      "sourcePage": 3,
      "ingestionStatus": "image_required",
      "requiresMedia": true,
      "mediaType": "cartoon",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-ESP-01",
      "questionNumber": 1,
      "languageTrack": "spanish",
      "area": "languages",
      "answerKey": "A",
      "sourcePage": 4,
      "ingestionStatus": "image_required",
      "requiresMedia": true,
      "mediaType": "poster",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-ESP-02",
      "questionNumber": 2,
      "languageTrack": "spanish",
      "area": "languages",
      "answerKey": "A",
      "sourcePage": 4,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-ESP-03",
      "questionNumber": 3,
      "languageTrack": "spanish",
      "area": "languages",
      "answerKey": "E",
      "sourcePage": 5,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-ESP-04",
      "questionNumber": 4,
      "languageTrack": "spanish",
      "area": "languages",
      "answerKey": "B",
      "sourcePage": 5,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-ESP-05",
      "questionNumber": 5,
      "languageTrack": "spanish",
      "area": "languages",
      "answerKey": "A",
      "sourcePage": 5,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q06",
      "questionNumber": 6,
      "languageTrack": null,
      "area": "languages",
      "answerKey": "D",
      "sourcePage": 6,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q07",
      "questionNumber": 7,
      "languageTrack": null,
      "area": "languages",
      "answerKey": "A",
      "sourcePage": 6,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q08",
      "questionNumber": 8,
      "languageTrack": null,
      "area": "languages",
      "answerKey": "C",
      "sourcePage": 6,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q09",
      "questionNumber": 9,
      "languageTrack": null,
      "area": "languages",
      "answerKey": "E",
      "sourcePage": 7,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q10",
      "questionNumber": 10,
      "languageTrack": null,
      "area": "languages",
      "answerKey": "E",
      "sourcePage": 7,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q11",
      "questionNumber": 11,
      "languageTrack": null,
      "area": "languages",
      "answerKey": "D",
      "sourcePage": 7,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q12",
      "questionNumber": 12,
      "languageTrack": null,
      "area": "languages",
      "answerKey": "C",
      "sourcePage": 8,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q13",
      "questionNumber": 13,
      "languageTrack": null,
      "area": "languages",
      "answerKey": "C",
      "sourcePage": 8,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q14",
      "questionNumber": 14,
      "languageTrack": null,
      "area": "languages",
      "answerKey": "D",
      "sourcePage": 9,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q15",
      "questionNumber": 15,
      "languageTrack": null,
      "area": "languages",
      "answerKey": "B",
      "sourcePage": 9,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q16",
      "questionNumber": 16,
      "languageTrack": null,
      "area": "languages",
      "answerKey": "A",
      "sourcePage": 10,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q17",
      "questionNumber": 17,
      "languageTrack": null,
      "area": "languages",
      "answerKey": "D",
      "sourcePage": 10,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q18",
      "questionNumber": 18,
      "languageTrack": null,
      "area": "languages",
      "answerKey": "B",
      "sourcePage": 10,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q19",
      "questionNumber": 19,
      "languageTrack": null,
      "area": "languages",
      "answerKey": "D",
      "sourcePage": 11,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q20",
      "questionNumber": 20,
      "languageTrack": null,
      "area": "languages",
      "answerKey": "E",
      "sourcePage": 11,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q21",
      "questionNumber": 21,
      "languageTrack": null,
      "area": "languages",
      "answerKey": "D",
      "sourcePage": 11,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q22",
      "questionNumber": 22,
      "languageTrack": null,
      "area": "languages",
      "answerKey": "C",
      "sourcePage": 12,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q23",
      "questionNumber": 23,
      "languageTrack": null,
      "area": "languages",
      "answerKey": "C",
      "sourcePage": 12,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q24",
      "questionNumber": 24,
      "languageTrack": null,
      "area": "languages",
      "answerKey": "E",
      "sourcePage": 12,
      "ingestionStatus": "image_required",
      "requiresMedia": true,
      "mediaType": "public_service_ad",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q25",
      "questionNumber": 25,
      "languageTrack": null,
      "area": "languages",
      "answerKey": "B",
      "sourcePage": 13,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q26",
      "questionNumber": 26,
      "languageTrack": null,
      "area": "languages",
      "answerKey": "C",
      "sourcePage": 13,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q27",
      "questionNumber": 27,
      "languageTrack": null,
      "area": "languages",
      "answerKey": "A",
      "sourcePage": 13,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q28",
      "questionNumber": 28,
      "languageTrack": null,
      "area": "languages",
      "answerKey": "C",
      "sourcePage": 13,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q29",
      "questionNumber": 29,
      "languageTrack": null,
      "area": "languages",
      "answerKey": "E",
      "sourcePage": 14,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q30",
      "questionNumber": 30,
      "languageTrack": null,
      "area": "languages",
      "answerKey": "A",
      "sourcePage": 14,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q31",
      "questionNumber": 31,
      "languageTrack": null,
      "area": "languages",
      "answerKey": "C",
      "sourcePage": 14,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q32",
      "questionNumber": 32,
      "languageTrack": null,
      "area": "languages",
      "answerKey": "A",
      "sourcePage": 15,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q33",
      "questionNumber": 33,
      "languageTrack": null,
      "area": "languages",
      "answerKey": "A",
      "sourcePage": 15,
      "ingestionStatus": "image_required",
      "requiresMedia": true,
      "mediaType": "artwork",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q34",
      "questionNumber": 34,
      "languageTrack": null,
      "area": "languages",
      "answerKey": "C",
      "sourcePage": 15,
      "ingestionStatus": "image_required",
      "requiresMedia": true,
      "mediaType": "performance_photo",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q35",
      "questionNumber": 35,
      "languageTrack": null,
      "area": "languages",
      "answerKey": "A",
      "sourcePage": 16,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q36",
      "questionNumber": 36,
      "languageTrack": null,
      "area": "languages",
      "answerKey": "A",
      "sourcePage": 16,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q37",
      "questionNumber": 37,
      "languageTrack": null,
      "area": "languages",
      "answerKey": "C",
      "sourcePage": 16,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q38",
      "questionNumber": 38,
      "languageTrack": null,
      "area": "languages",
      "answerKey": "A",
      "sourcePage": 16,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q39",
      "questionNumber": 39,
      "languageTrack": null,
      "area": "languages",
      "answerKey": "C",
      "sourcePage": 17,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q40",
      "questionNumber": 40,
      "languageTrack": null,
      "area": "languages",
      "answerKey": "B",
      "sourcePage": 17,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q41",
      "questionNumber": 41,
      "languageTrack": null,
      "area": "languages",
      "answerKey": "B",
      "sourcePage": 17,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q42",
      "questionNumber": 42,
      "languageTrack": null,
      "area": "languages",
      "answerKey": "E",
      "sourcePage": 17,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q43",
      "questionNumber": 43,
      "languageTrack": null,
      "area": "languages",
      "answerKey": "A",
      "sourcePage": 18,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q44",
      "questionNumber": 44,
      "languageTrack": null,
      "area": "languages",
      "answerKey": "A",
      "sourcePage": 18,
      "ingestionStatus": "image_required",
      "requiresMedia": true,
      "mediaType": "public_health_ad",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q45",
      "questionNumber": 45,
      "languageTrack": null,
      "area": "languages",
      "answerKey": "E",
      "sourcePage": 18,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q46",
      "questionNumber": 46,
      "languageTrack": null,
      "area": "human_sciences",
      "answerKey": "C",
      "sourcePage": 20,
      "ingestionStatus": "image_required",
      "requiresMedia": true,
      "mediaType": "embroidered_photo",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q47",
      "questionNumber": 47,
      "languageTrack": null,
      "area": "human_sciences",
      "answerKey": "D",
      "sourcePage": 20,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q48",
      "questionNumber": 48,
      "languageTrack": null,
      "area": "human_sciences",
      "answerKey": "A",
      "sourcePage": 20,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q49",
      "questionNumber": 49,
      "languageTrack": null,
      "area": "human_sciences",
      "answerKey": "E",
      "sourcePage": 20,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q50",
      "questionNumber": 50,
      "languageTrack": null,
      "area": "human_sciences",
      "answerKey": "E",
      "sourcePage": 21,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q51",
      "questionNumber": 51,
      "languageTrack": null,
      "area": "human_sciences",
      "answerKey": "C",
      "sourcePage": 21,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q52",
      "questionNumber": 52,
      "languageTrack": null,
      "area": "human_sciences",
      "answerKey": "A",
      "sourcePage": 21,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q53",
      "questionNumber": 53,
      "languageTrack": null,
      "area": "human_sciences",
      "answerKey": "B",
      "sourcePage": 21,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q54",
      "questionNumber": 54,
      "languageTrack": null,
      "area": "human_sciences",
      "answerKey": "A",
      "sourcePage": 21,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q55",
      "questionNumber": 55,
      "languageTrack": null,
      "area": "human_sciences",
      "answerKey": "A",
      "sourcePage": 22,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q56",
      "questionNumber": 56,
      "languageTrack": null,
      "area": "human_sciences",
      "answerKey": "C",
      "sourcePage": 22,
      "ingestionStatus": "image_required",
      "requiresMedia": true,
      "mediaType": "comic_strip",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q57",
      "questionNumber": 57,
      "languageTrack": null,
      "area": "human_sciences",
      "answerKey": "E",
      "sourcePage": 22,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q58",
      "questionNumber": 58,
      "languageTrack": null,
      "area": "human_sciences",
      "answerKey": "A",
      "sourcePage": 23,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q59",
      "questionNumber": 59,
      "languageTrack": null,
      "area": "human_sciences",
      "answerKey": "A",
      "sourcePage": 23,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q60",
      "questionNumber": 60,
      "languageTrack": null,
      "area": "human_sciences",
      "answerKey": "D",
      "sourcePage": 23,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q61",
      "questionNumber": 61,
      "languageTrack": null,
      "area": "human_sciences",
      "answerKey": "E",
      "sourcePage": 23,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q62",
      "questionNumber": 62,
      "languageTrack": null,
      "area": "human_sciences",
      "answerKey": "C",
      "sourcePage": 24,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q63",
      "questionNumber": 63,
      "languageTrack": null,
      "area": "human_sciences",
      "answerKey": "B",
      "sourcePage": 24,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q64",
      "questionNumber": 64,
      "languageTrack": null,
      "area": "human_sciences",
      "answerKey": "D",
      "sourcePage": 24,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q65",
      "questionNumber": 65,
      "languageTrack": null,
      "area": "human_sciences",
      "answerKey": "A",
      "sourcePage": 24,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q66",
      "questionNumber": 66,
      "languageTrack": null,
      "area": "human_sciences",
      "answerKey": "A",
      "sourcePage": 25,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q67",
      "questionNumber": 67,
      "languageTrack": null,
      "area": "human_sciences",
      "answerKey": "B",
      "sourcePage": 25,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q68",
      "questionNumber": 68,
      "languageTrack": null,
      "area": "human_sciences",
      "answerKey": "C",
      "sourcePage": 25,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q69",
      "questionNumber": 69,
      "languageTrack": null,
      "area": "human_sciences",
      "answerKey": "D",
      "sourcePage": 25,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q70",
      "questionNumber": 70,
      "languageTrack": null,
      "area": "human_sciences",
      "answerKey": "C",
      "sourcePage": 26,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q71",
      "questionNumber": 71,
      "languageTrack": null,
      "area": "human_sciences",
      "answerKey": "A",
      "sourcePage": 26,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q72",
      "questionNumber": 72,
      "languageTrack": null,
      "area": "human_sciences",
      "answerKey": "B",
      "sourcePage": 26,
      "ingestionStatus": "image_required",
      "requiresMedia": true,
      "mediaType": "comic_strip",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q73",
      "questionNumber": 73,
      "languageTrack": null,
      "area": "human_sciences",
      "answerKey": "A",
      "sourcePage": 27,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q74",
      "questionNumber": 74,
      "languageTrack": null,
      "area": "human_sciences",
      "answerKey": "D",
      "sourcePage": 27,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q75",
      "questionNumber": 75,
      "languageTrack": null,
      "area": "human_sciences",
      "answerKey": "C",
      "sourcePage": 27,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q76",
      "questionNumber": 76,
      "languageTrack": null,
      "area": "human_sciences",
      "answerKey": "D",
      "sourcePage": 27,
      "ingestionStatus": "image_required",
      "requiresMedia": true,
      "mediaType": "chart",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q77",
      "questionNumber": 77,
      "languageTrack": null,
      "area": "human_sciences",
      "answerKey": "E",
      "sourcePage": 28,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q78",
      "questionNumber": 78,
      "languageTrack": null,
      "area": "human_sciences",
      "answerKey": "A",
      "sourcePage": 28,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q79",
      "questionNumber": 79,
      "languageTrack": null,
      "area": "human_sciences",
      "answerKey": "B",
      "sourcePage": 28,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q80",
      "questionNumber": 80,
      "languageTrack": null,
      "area": "human_sciences",
      "answerKey": "A",
      "sourcePage": 28,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q81",
      "questionNumber": 81,
      "languageTrack": null,
      "area": "human_sciences",
      "answerKey": "A",
      "sourcePage": 29,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q82",
      "questionNumber": 82,
      "languageTrack": null,
      "area": "human_sciences",
      "answerKey": "B",
      "sourcePage": 29,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q83",
      "questionNumber": 83,
      "languageTrack": null,
      "area": "human_sciences",
      "answerKey": "C",
      "sourcePage": 29,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q84",
      "questionNumber": 84,
      "languageTrack": null,
      "area": "human_sciences",
      "answerKey": "D",
      "sourcePage": 29,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q85",
      "questionNumber": 85,
      "languageTrack": null,
      "area": "human_sciences",
      "answerKey": "D",
      "sourcePage": 30,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q86",
      "questionNumber": 86,
      "languageTrack": null,
      "area": "human_sciences",
      "answerKey": "E",
      "sourcePage": 30,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q87",
      "questionNumber": 87,
      "languageTrack": null,
      "area": "human_sciences",
      "answerKey": "B",
      "sourcePage": 30,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q88",
      "questionNumber": 88,
      "languageTrack": null,
      "area": "human_sciences",
      "answerKey": "A",
      "sourcePage": 30,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q89",
      "questionNumber": 89,
      "languageTrack": null,
      "area": "human_sciences",
      "answerKey": "D",
      "sourcePage": 31,
      "ingestionStatus": "image_required",
      "requiresMedia": true,
      "mediaType": "climate_maps",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    },
    {
      "externalId": "ENEM-2023-D1-C1-Q90",
      "questionNumber": 90,
      "languageTrack": null,
      "area": "human_sciences",
      "answerKey": "B",
      "sourcePage": 31,
      "ingestionStatus": "ready_text",
      "requiresMedia": false,
      "mediaType": "none",
      "originType": "official_exam",
      "verified": false,
      "sourceVerified": true,
      "verificationNote": "Fonte e gabarito oficiais conferidos; manter false até a transcrição completa e a validação do enunciado, alternativas e mídia."
    }
  ],
  "essayPrompt": {
    "externalId": "ENEM-2023-D1-C1-REDACAO",
    "area": "writing",
    "sourcePage": 19,
    "ingestionStatus": "separate_module",
    "originType": "official_exam",
    "verified": false,
    "theme": "Desafios para o enfrentamento da invisibilidade do trabalho de cuidado realizado pela mulher no Brasil",
    "sourceVerified": true,
    "verificationNote": "Fonte oficial conferida; manter false até a transcrição e validação completas dos textos motivadores e recursos visuais."
  }
} as const;
